- menu_name: "Services"

- name: "Contact"
  url: "/contact/"
  class: "services-contact"
  title: "Contact"

- name: "Developers"
  url: "/developers/"
  class: "list"
  title: "Contact the developers"
